name: Deploy to AWS ECS

on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: laravel-blog-app
  ECS_SERVICE: laravel-blog-service
  ECS_CLUSTER: laravel-blog-cluster
  ECS_TASK_DEFINITION: laravel-blog-task
  CONTAINER_NAME: laravel-app

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel_test
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, redis
    
    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest
        npm install
        npm run build
    
    - name: Setup environment
      run: |
        cp .env.example .env
        php artisan key:generate
    
    - name: Run Pint (Code Style Check)
      run: ./vendor/bin/pint --preset psr12 --test
    
    - name: Configure test database
      run: |
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=laravel_test" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=password" >> .env
        php artisan config:clear
        cat .env
    
    - name: Wait for services
      run: |
        echo "Waiting for MySQL..."
        while ! mysqladmin ping -h"127.0.0.1" -P"3306" -u"root" -p"password" --silent; do
          sleep 2
        done
        echo "MySQL is ready!"
            
    - name: Run tests
      run: |
        php artisan migrate --force
        php artisan test